defmodule L2E.LoginServer.SessionKey do
  @moduledoc """
  Immutable session key generated by the Login Server.

  Four random 32-bit values in two pairs:

  - **LoginOk pair** (login_ok1 / login_ok2): sent in `LoginOk`, verified
    by the client in `RequestServerList` and `RequestServerLogin`.
  - **PlayOk pair** (play_ok1 / play_ok2): sent in `PlayOk`, forwarded by
    the client to the Game Server in `AuthLogin`.

  The Game Server verifies the PlayOk pair against the `AccountStore` to
  confirm the client went through a legitimate Login Server session.

  Reference: `loginserver/SessionKey.java`
  """

  defstruct [:login_ok1, :login_ok2, :play_ok1, :play_ok2]

  @type t :: %__MODULE__{
          login_ok1: non_neg_integer(),
          login_ok2: non_neg_integer(),
          play_ok1: non_neg_integer(),
          play_ok2: non_neg_integer()
        }

  @spec new() :: t()
  def new do
    %__MODULE__{
      login_ok1: :rand.uniform(0x7FFFFFFF),
      login_ok2: :rand.uniform(0x7FFFFFFF),
      play_ok1: :rand.uniform(0x7FFFFFFF),
      play_ok2: :rand.uniform(0x7FFFFFFF)
    }
  end

  @spec check_login_pair(t(), integer(), integer()) :: boolean()
  def check_login_pair(%__MODULE__{login_ok1: l1, login_ok2: l2}, key1, key2),
    do: l1 == key1 and l2 == key2

  @spec check_play_pair(t(), integer(), integer()) :: boolean()
  def check_play_pair(%__MODULE__{play_ok1: p1, play_ok2: p2}, key1, key2),
    do: p1 == key1 and p2 == key2
end
